nav:
    - Home: index.md
    - Getting Started : getting_started.md
    - 'Contributors':
      - 'About Contributors' : 'contributors/about_contributors.md'
      - 'Tools and Processes' : 'contributors/tools_and_processes.md'
    - Roadmaps : roadmaps.md
    - 'Developer Guide':
      - 'Design and Architecture' : 'developer_guide/software_reference/design_and_architecture.md'
      - 'Graphics Engine' : 'developer_guide/software_reference/graphics_engine.md'
      - 'Software Reference':
        - 'hierarch_data.gd' : 'developer_guide/software_reference/hierarch_data.md'



theme:
  name: material
  logo: 'images/Logo_W.png'
  palette:
    scheme: slate
    primary: brown
    accent: deep_orange

site_name: 'Corpusim Docs'
repo_name: 'Corpusim Docs Repo'
site_url: https://docs.corpusim.com

plugins:
  - git-revision-date
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      puml_keyword: plantuml

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
